export const initialTaskList = [
  {
    id: '0',
    name: 'Alexandre Mercier',
    email: 'alexandremercier@mail.com',
    text: 'AUTH-4021',
    isDone: false,
    isEdited: false,
  },
  {
    id: '1',
    name: 'Hiroshi Tanaka',
    email: 'hiroshitanaka@mail.com',
    text: 'PAY-1089',
    isDone: true,
    isEdited: false,
  },
  {
    id: '2',
    name: 'Matteo Bianchi',
    email: 'matteobianchi@mail.com',
    text: 'INFRA-8832',
    isDone: false,
    isEdited: true,
  },
  {
    id: '3',
    name: 'Santiago Garcia',
    email: 'santiagogarcia@mail.com',
    text: 'FRONT-1204',
    isDone: true,
    isEdited: true,
  },
  {
    id: '4',
    name: 'Henrik Lindqvist',
    email: 'henriklindqvist@mail.com',
    text: 'CORE-5531',
    isDone: false,
    isEdited: false,
  },
  {
    id: '5',
    name: 'Rajesh Sharma',
    email: 'rajeshsharma@mail.com',
    text: 'DATA-3310',
    isDone: true,
    isEdited: false,
  },
  {
    id: '6',
    name: 'Julien Bernard',
    email: 'julienbernard@mail.com',
    text: 'SEC-9012',
    isDone: false,
    isEdited: false,
  },
  {
    id: '7',
    name: 'Thomas Weber',
    email: 'thomasweber@mail.com',
    text: 'INC-20260830-8A4F',
    isDone: true,
    isEdited: true,
  },
  {
    id: '8',
    name: 'Wei Zhang',
    email: 'weizhang@mail.com',
    text: 'ALT-REDIS-B3F901',
    isDone: false,
    isEdited: false,
  },
  {
    id: '9',
    name: 'Mehmet Yilmaz',
    email: 'mehmetyilmaz@mail.com',
    text: 'CHG-004921',
    isDone: true,
    isEdited: false,
  },
  {
    id: '10',
    name: 'Sofia Fernandez',
    email: 'sofiafernandez@mail.com',
    text: 'API-7721',
    isDone: false,
    isEdited: true,
  },
  {
    id: '11',
    name: 'Arjun Patel',
    email: 'arjunpatel@mail.com',
    text: 'MOB-3091',
    isDone: false,
    isEdited: false,
  },
  {
    id: '12',
    name: 'Camille Laurent',
    email: 'camillelaurent@mail.com',
    text: 'BILL-4412',
    isDone: true,
    isEdited: true,
  },
  {
    id: '13',
    name: 'Mateo Morales',
    email: 'mateomorales@mail.com',
    text: 'DEVOPS-6102',
    isDone: false,
    isEdited: false,
  },
  {
    id: '14',
    name: 'Kenji Takahashi',
    email: 'kenjitakahashi@mail.com',
    text: 'NOTIF-8201',
    isDone: true,
    isEdited: false,
  },
  {
    id: '15',
    name: 'Hannah Fischer',
    email: 'hannahfischer@mail.com',
    text: 'SEARCH-1190',
    isDone: true,
    isEdited: true,
  },
  {
    id: '16',
    name: 'David Osei',
    email: 'davidosei@mail.com',
    text: 'ML-9904',
    isDone: false,
    isEdited: true,
  },
  {
    id: '17',
    name: 'Piotr Kowalczyk',
    email: 'piotrkowalczyk@mail.com',
    text: 'ANALYTICS-2041',
    isDone: true,
    isEdited: false,
  },
  {
    id: '18',
    name: 'Astrid Nilsson',
    email: 'astridnilsson@mail.com',
    text: 'INC-20260831-9F1C',
    isDone: false,
    isEdited: false,
  },
  {
    id: '19',
    name: 'Lucas Petit',
    email: 'lucaspetit@mail.com',
    text: 'ALT-K8S-C4D812',
    isDone: true,
    isEdited: true,
  },
  {
    id: '20',
    name: 'Tariq Al-Hassan',
    email: 'tariqalhassan@mail.com',
    text: 'CHG-005110',
    isDone: false,
    isEdited: false,
  },
  {
    id: '21',
    name: 'Jan De Jong',
    email: 'jandejong@mail.com',
    text: 'CHAT-3341',
    isDone: true,
    isEdited: false,
  },
  {
    id: '22',
    name: 'Johan Eriksson',
    email: 'johaneriksson@mail.com',
    text: 'CRM-1092',
    isDone: false,
    isEdited: true,
  },
  {
    id: '23',
    name: 'Li Wang',
    email: 'liwang@mail.com',
    text: 'ERP-7781',
    isDone: false,
    isEdited: false,
  },
  {
    id: '24',
    name: 'Gabriel Silva',
    email: 'gabrielsilva@mail.com',
    text: 'LOG-4099',
    isDone: true,
    isEdited: true,
  },
  {
    id: '25',
    name: 'Freja Jensen',
    email: 'frejajensen@mail.com',
    text: 'CACHE-8812',
    isDone: false,
    isEdited: true,
  },
  {
    id: '26',
    name: 'Sean Murphy',
    email: 'seanmurphy@mail.com',
    text: 'REG-1520',
    isDone: true,
    isEdited: false,
  },
  {
    id: '27',
    name: 'Amara Okafor',
    email: 'amaraokafor@mail.com',
    text: 'MEDIA-6610',
    isDone: false,
    isEdited: false,
  },
  {
    id: '28',
    name: 'Markus Hoffmann',
    email: 'markushoffmann@mail.com',
    text: 'MAP-3301',
    isDone: true,
    isEdited: false,
  },
  {
    id: '29',
    name: 'Elif Demir',
    email: 'elifdemir@mail.com',
    text: 'GW-9099',
    isDone: false,
    isEdited: true,
  },
  {
    id: '30',
    name: 'Tomas Dvorak',
    email: 'tomasdvorak@mail.com',
    text: 'SCHED-4120',
    isDone: true,
    isEdited: true,
  },
  {
    id: '31',
    name: 'Amina Kamara',
    email: 'aminakamara@mail.com',
    text: 'AUTH-5022',
    isDone: false,
    isEdited: false,
  },
  {
    id: '32',
    name: 'Minh Tran',
    email: 'minhtran@mail.com',
    text: 'PAY-2090',
    isDone: true,
    isEdited: false,
  },
  {
    id: '33',
    name: 'Maja Hansen',
    email: 'majahansen@mail.com',
    text: 'INFRA-9001',
    isDone: false,
    isEdited: true,
  },
  {
    id: '34',
    name: 'Daniel Gomez',
    email: 'danielgomez@mail.com',
    text: 'FRONT-3410',
    isDone: true,
    isEdited: true,
  },
  {
    id: '35',
    name: 'Yuto Suzuki',
    email: 'yutosuzuki@mail.com',
    text: 'CORE-6612',
    isDone: false,
    isEdited: false,
  },
  {
    id: '36',
    name: 'Alexei Morozov',
    email: 'alexeimorozov@mail.com',
    text: 'INC-20260901-1A2B',
    isDone: false,
    isEdited: true,
  },
  {
    id: '37',
    name: 'Sarah Miller',
    email: 'sarahmiller@mail.com',
    text: 'ALT-DB-E9F011',
    isDone: true,
    isEdited: false,
  },
  {
    id: '38',
    name: 'Vikram Singh',
    email: 'vikramsingh@mail.com',
    text: 'CHG-006200',
    isDone: true,
    isEdited: true,
  },
  {
    id: '39',
    name: 'Layla Mansour',
    email: 'laylamansour@mail.com',
    text: 'DATA-4490',
    isDone: false,
    isEdited: false,
  },
  {
    id: '40',
    name: 'Andrea Ricci',
    email: 'andrearicci@mail.com',
    text: 'SEC-1120',
    isDone: true,
    isEdited: false,
  },
  {
    id: '41',
    name: 'Omer Cohen',
    email: 'omercohen@mail.com',
    text: 'API-8830',
    isDone: false,
    isEdited: false,
  },
  {
    id: '42',
    name: 'Arthur Davies',
    email: 'arthurdavies@mail.com',
    text: 'MOB-4112',
    isDone: true,
    isEdited: true,
  },
  {
    id: '43',
    name: 'Javier Ortiz',
    email: 'javierortiz@mail.com',
    text: 'BILL-5501',
    isDone: false,
    isEdited: true,
  },
  {
    id: '44',
    name: 'Chen Xiu',
    email: 'chenxiu@mail.com',
    text: 'DEVOPS-7210',
    isDone: true,
    isEdited: false,
  },
  {
    id: '45',
    name: 'Sanjay Verma',
    email: 'sanjayverma@mail.com',
    text: 'NOTIF-9311',
    isDone: false,
    isEdited: false,
  },
  {
    id: '46',
    name: 'Emma Taylor',
    email: 'emmataylor@mail.com',
    text: 'SEARCH-2201',
    isDone: true,
    isEdited: true,
  },
  {
    id: '47',
    name: 'Martin Novak',
    email: 'martinnovak@mail.com',
    text: 'ML-1044',
    isDone: false,
    isEdited: false,
  },
  {
    id: '48',
    name: 'Julia Schneider',
    email: 'juliaschneider@mail.com',
    text: 'ANALYTICS-3199',
    isDone: true,
    isEdited: true,
  },
  {
    id: '49',
    name: 'Gonzalo Romero',
    email: 'gonzaloromero@mail.com',
    text: 'CHAT-4510',
    isDone: false,
    isEdited: true,
  },
  {
    id: '50',
    name: 'Lars Visser',
    email: 'larsvisser@mail.com',
    text: 'CRM-2280',
    isDone: true,
    isEdited: false,
  },
  {
    id: '51',
    name: 'Yang Lei',
    email: 'yanglei@mail.com',
    text: 'ERP-8901',
    isDone: false,
    isEdited: false,
  },
  {
    id: '52',
    name: 'Bilal Ahmed',
    email: 'bilalahmed@mail.com',
    text: 'LOG-5120',
    isDone: true,
    isEdited: true,
  },
  {
    id: '53',
    name: 'Chloe Martin',
    email: 'chloemartin@mail.com',
    text: 'CACHE-9911',
    isDone: false,
    isEdited: true,
  },
  {
    id: '54',
    name: 'Robert Evans',
    email: 'robertevans@mail.com',
    text: 'INC-20260902-77AA',
    isDone: false,
    isEdited: false,
  },
  {
    id: '55',
    name: 'Beatrice Conti',
    email: 'beatriceconti@mail.com',
    text: 'ALT-MEM-A11B22',
    isDone: true,
    isEdited: false,
  },
  {
    id: '56',
    name: 'Carlos Delgado',
    email: 'carlosdelgado@mail.com',
    text: 'CHG-007812',
    isDone: true,
    isEdited: true,
  },
  {
    id: '57',
    name: 'Elena Volkova',
    email: 'elenavolkova@mail.com',
    text: 'REG-2610',
    isDone: false,
    isEdited: false,
  },
  {
    id: '58',
    name: 'Filip Horvat',
    email: 'filiphorvat@mail.com',
    text: 'MEDIA-7711',
    isDone: true,
    isEdited: true,
  },
  {
    id: '59',
    name: 'Niamh Kelly',
    email: 'niamhkelly@mail.com',
    text: 'MAP-4420',
    isDone: false,
    isEdited: true,
  },
  {
    id: '60',
    name: 'Gustav Larsson',
    email: 'gustavlarsson@mail.com',
    text: 'GW-1010',
    isDone: true,
    isEdited: false,
  },
  {
    id: '61',
    name: 'Kareem Said',
    email: 'kareemsaid@mail.com',
    text: 'SCHED-5201',
    isDone: false,
    isEdited: false,
  },
  {
    id: '62',
    name: 'Ines Santos',
    email: 'inessantos@mail.com',
    text: 'AUTH-6120',
    isDone: true,
    isEdited: true,
  },
  {
    id: '63',
    name: 'Benjamin Brooks',
    email: 'benjaminbrooks@mail.com',
    text: 'PAY-3112',
    isDone: false,
    isEdited: true,
  },
  {
    id: '64',
    name: 'Signe Pedersen',
    email: 'signepedersen@mail.com',
    text: 'INFRA-1099',
    isDone: false,
    isEdited: false,
  },
  {
    id: '65',
    name: 'Marco Esposito',
    email: 'marcoesposito@mail.com',
    text: 'FRONT-4521',
    isDone: true,
    isEdited: false,
  },
  {
    id: '66',
    name: 'Naomi Nwosu',
    email: 'naominwosu@mail.com',
    text: 'CORE-7731',
    isDone: true,
    isEdited: true,
  },
  {
    id: '67',
    name: 'Oliver Smith',
    email: 'oliversmith@mail.com',
    text: 'DATA-5502',
    isDone: false,
    isEdited: false,
  },
  {
    id: '68',
    name: 'Olga Semyonova',
    email: 'olgasemyonova@mail.com',
    text: 'INC-20260903-33CC',
    isDone: false,
    isEdited: true,
  },
  {
    id: '69',
    name: 'Manuel Costa',
    email: 'manuelcosta@mail.com',
    text: 'ALT-CPU-FF0011',
    isDone: true,
    isEdited: false,
  },
  {
    id: '70',
    name: 'Philip Baker',
    email: 'philipbaker@mail.com',
    text: 'CHG-008901',
    isDone: true,
    isEdited: true,
  },
  {
    id: '71',
    name: 'Maria Kowalska',
    email: 'mariakowalska@mail.com',
    text: 'SEC-2231',
    isDone: false,
    isEdited: false,
  },
  {
    id: '72',
    name: 'Naoki Sato',
    email: 'naokisato@mail.com',
    text: 'API-9901',
    isDone: true,
    isEdited: false,
  },
  {
    id: '73',
    name: 'Samir Khan',
    email: 'samirkhan@mail.com',
    text: 'MOB-5221',
    isDone: false,
    isEdited: true,
  },
  {
    id: '74',
    name: 'Rashid Al-Farsi',
    email: 'rashidalfarsi@mail.com',
    text: 'BILL-6612',
    isDone: true,
    isEdited: true,
  },
  {
    id: '75',
    name: 'Grace Turner',
    email: 'graceturner@mail.com',
    text: 'DEVOPS-8321',
    isDone: false,
    isEdited: false,
  },
  {
    id: '76',
    name: 'Edward Harris',
    email: 'edwardharris@mail.com',
    text: 'NOTIF-1090',
    isDone: true,
    isEdited: false,
  },
  {
    id: '77',
    name: 'Valeria Reyes',
    email: 'valeriareyes@mail.com',
    text: 'SEARCH-3312',
    isDone: false,
    isEdited: true,
  },
  {
    id: '78',
    name: 'Jun Lin',
    email: 'junlin@mail.com',
    text: 'ML-2104',
    isDone: true,
    isEdited: false,
  },
  {
    id: '79',
    name: 'Peter Hudak',
    email: 'peterhudak@mail.com',
    text: 'ANALYTICS-4210',
    isDone: false,
    isEdited: false,
  },
  {
    id: '80',
    name: 'Chidubem Eze',
    email: 'chidubemeze@mail.com',
    text: 'CHAT-5621',
    isDone: true,
    isEdited: true,
  },
  {
    id: '81',
    name: 'Erik Berg',
    email: 'erikberg@mail.com',
    text: 'CRM-3391',
    isDone: false,
    isEdited: true,
  },
  {
    id: '82',
    name: 'Hanna Schmidt',
    email: 'hannaschmidt@mail.com',
    text: 'ERP-9912',
    isDone: true,
    isEdited: false,
  },
  {
    id: '83',
    name: 'Ivan Smirnov',
    email: 'ivansmirnov@mail.com',
    text: 'INC-20260904-44DD',
    isDone: false,
    isEdited: false,
  },
  {
    id: '84',
    name: 'Luciana Moretti',
    email: 'lucianamoretti@mail.com',
    text: 'ALT-DISK-EE2233',
    isDone: true,
    isEdited: true,
  },
  {
    id: '85',
    name: 'Isabel Vargas',
    email: 'isabelvargas@mail.com',
    text: 'CHG-009112',
    isDone: false,
    isEdited: false,
  },
  {
    id: '86',
    name: 'Matteo De Luca',
    email: 'matteodeluca@mail.com',
    text: 'LOG-6231',
    isDone: true,
    isEdited: false,
  },
  {
    id: '87',
    name: 'Antti Heikkinen',
    email: 'anttiheikkinen@mail.com',
    text: 'CACHE-1120',
    isDone: false,
    isEdited: true,
  },
  {
    id: '88',
    name: 'Friedrich Bauer',
    email: 'friedrichbauer@mail.com',
    text: 'REG-3721',
    isDone: true,
    isEdited: true,
  },
  {
    id: '89',
    name: 'Fernando Gomez',
    email: 'fernandogomez@mail.com',
    text: 'MEDIA-8820',
    isDone: false,
    isEdited: false,
  },
  {
    id: '90',
    name: 'Ekaterina Popova',
    email: 'ekaterinapopova@mail.com',
    text: 'MAP-5531',
    isDone: true,
    isEdited: false,
  },
  {
    id: '91',
    name: 'Vasily Vasiliev',
    email: 'vasilyvasiliev@mail.com',
    text: 'GW-2121',
    isDone: false,
    isEdited: true,
  },
  {
    id: '92',
    name: 'Francesca Romano',
    email: 'francescaromano@mail.com',
    text: 'SCHED-6310',
    isDone: true,
    isEdited: true,
  },
  {
    id: '93',
    name: 'Lucas Silva',
    email: 'lucassilva@mail.com',
    text: 'AUTH-7231',
    isDone: false,
    isEdited: false,
  },
  {
    id: '94',
    name: 'Otto Richter',
    email: 'ottorichter@mail.com',
    text: 'PAY-4220',
    isDone: true,
    isEdited: false,
  },
  {
    id: '95',
    name: 'Carmen Navarro',
    email: 'carmennavarro@mail.com',
    text: 'INFRA-2101',
    isDone: false,
    isEdited: true,
  },
  {
    id: '96',
    name: 'Rafael Torres',
    email: 'rafaeltorres@mail.com',
    text: 'FRONT-5631',
    isDone: true,
    isEdited: false,
  },
  {
    id: '97',
    name: 'Jennifer Clark',
    email: 'jenniferclark@mail.com',
    text: 'CORE-8841',
    isDone: false,
    isEdited: false,
  },
  {
    id: '98',
    name: 'Antoine Dubois',
    email: 'antoinedubois@mail.com',
    text: 'DATA-6611',
    isDone: true,
    isEdited: true,
  },
  {
    id: '99',
    name: 'Ryan Cooper',
    email: 'ryancooper@mail.com',
    text: 'SEC-3342',
    isDone: false,
    isEdited: true,
  },
];
