export const typeOptions = [
    { value: `АВГ`, label: `АВГ` },
    { value: `2АВГ`, label: `2АВГ` },
    { value: `АВГ-В`, label: `АВГ-В` },
    { value: `1АВГ-ВВП`, label: `1АВГ-ВВП` },
    { value: `2АВГ-75`, label: `2АВГ-75` },
    { value: `2АВГ-100`, label: `2АВГ-100` },
    { value: `АВГ-160Г`, label: `АВГ-160Г` },
    { value: `1АВГ-160`, label: `1АВГ-160` },
    { value: `АВЗ`, label: `АВЗ` },
    { value: `1АВЗ`, label: `1АВЗ` },
    { value: `АВЗ-Д`, label: `АВЗ-Д` },
    { value: `2АВЗ-Д`, label: `2АВЗ-Д` },
    { value: `АВМ-Г`, label: `АВМ-Г` },
    { value: `АВМ-В`, label: `АВМ-В` },
    { value: `АВОГ-1`, label: `АВОГ-1` },
];

export const finningOptions = [
    { value: `7`, label: `7` },
    { value: `7,8`, label: `7,8` },
    { value: `9`, label: `9` },
    { value: `14,6`, label: `14,6` },
    { value: `20`, label: `20` },
];

export const blindsOptions = [
    { value: `Ж`, label: `Ж` },
    { value: `ПЖ`, label: `ПЖ` },
    { value: `ЭЖ`, label: `ЭЖ` },
];

export const pressureOptions = [
    { value: `0,09`, label: `0,09 (0,9)` },
    { value: `0,6`, label: `0,6 (1,6)` },
    { value: `1,6`, label: `1,6 (16)` },
    { value: `2,5`, label: `2,5 (25)` },
    { value: `4,0`, label: `4,0 (40)` },
    { value: `6,3`, label: `6,3 (63)` },
    { value: `7,5`, label: `7,5 (75)` },
    { value: `10`, label: `10 (100)` },
    { value: `16`, label: `16 (160)` },
];

export const matExecOptions = [
    { value: `Б1`, label: `Б1` },
    { value: `Б2`, label: `Б2` },
    { value: `Б2.1`, label: `Б2.1` },
    { value: `Б3`, label: `Б3` },
    { value: `Б3.1`, label: `Б3.1` },
    { value: `Б4`, label: `Б4` },
    { value: `Б4.1`, label: `Б4.1` },
    { value: `Б5`, label: `Б5` },
    { value: `Б5.1`, label: `Б5.1` },
];

export const fanOptions = [
    { value: `Т1`, label: `Т1` },
    { value: `Т2`, label: `Т2` },
    { value: `Т3`, label: `Т3` },
    { value: `В1Т`, label: `В1Т` },
    { value: `В2Т`, label: `В2Т` },
    { value: `В3Т`, label: `В3Т` },
];

export const pipePerSectionOptions = [
    { value: `4`, label: `4` },
    { value: `6`, label: `6` },
    { value: `8`, label: `8` },
];

export const passageOptions = [
    { value: `1`, label: `1` },
    { value: `2`, label: `2` },
    { value: `2а`, label: `2а` },
    { value: `3`, label: `3` },
    { value: `3а`, label: `3а` },
    { value: `4`, label: `4` },
    { value: `4а`, label: `4а` },
    { value: `6`, label: `6` },
    { value: `8`, label: `8` },
    { value: `9`, label: `9` },
];

export const ribPipeLengthOptions = [
    { value: `1,5`, label: `1,5` },
    { value: `3`, label: `3` },
    { value: `4`, label: `4` },
    { value: `6`, label: `6` },
    { value: `8`, label: `8` },
    { value: `12`, label: `12` },
];

export const climateOptions = [
    { value: `УХЛ1`, label: `УХЛ1` },
    { value: `У1`, label: `У1` },
    { value: `С`, label: `С` },
];

export const ALLOW_RULES = {
    'АВГ': {
        finning: ['9', '14,6', '20'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['0,6', '1,6', '2,5', '4,0', '6,3'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: ['В1Т', 'В2Т', 'В3Т'],
        pipePerSection: ['4', '6', '8'],
        passage: ['1', '2', '2а', '3', '3а', '4', '4а', '6', '8'],
        ribPipeLength: ['4', '8'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    '2АВГ': {
        finning: ['9', '20'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['0,6', '1,6', '2,5', '4,0', '6,3'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: ['В1Т', 'В2Т', 'В3Т'],
        pipePerSection: ['4', '6'],
        passage: ['1', '2'],
        ribPipeLength: ['4', '8'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    'АВГ-В': {
        finning: ['7,8'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['0,6', '1,6', '2,5', '4,0', '6,3'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: ['В1Т', 'В2Т', 'В3Т'],
        pipePerSection: ['4', '6', '8'],
        passage: ['1', '2', '3', '4', '6'],
        ribPipeLength: ['4', '8'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    '1АВГ-ВВП': {
        finning: ['7'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['0,6', '1,6', '2,5', '4,0', '6,3'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: ['В2Т'],
        pipePerSection: ['4'],
        passage: ['9'],
        ribPipeLength: ['4'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    '2АВГ-75': {
        finning: ['20'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['7,5', '10'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: ['Т1'],
        pipePerSection: ['6'],
        passage: ['1'],
        ribPipeLength: ['12'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    '2АВГ-100': {
        finning: ['20'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['7,5', '10'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: ['Т1'],
        pipePerSection: ['6'],
        passage: ['1'],
        ribPipeLength: ['12'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    'АВГ-160Г': {
        finning: ['14,6', '20'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['16'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: ['Т3'],
        pipePerSection: ['4'],
        passage: ['2'],
        ribPipeLength: ['6'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    '1АВГ-160': {
        finning: ['20'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['16'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: ['В2Т'],
        pipePerSection: ['6'],
        passage: ['3'],
        ribPipeLength: ['8'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    'АВЗ': {
        finning: ['9', '14,6', '20'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['0,6', '1,6', '2,5', '4,0', '6,3'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: [],
        pipePerSection: ['4', '6', '8'],
        passage: ['1', '2', '2а', '4', '4а', '8'],
        ribPipeLength: ['6'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    '1АВЗ': {
        finning: ['9', '20'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['0,6', '1,6', '2,5', '4,0', '6,3'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: ['Т1', 'Т2', 'Т3'],
        pipePerSection: ['4', '6'],
        passage: ['1', '2', '2а', '4', '4а', '8'],
        ribPipeLength: ['6'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    'АВЗ-Д': {
        finning: ['9', '14,6', '20'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['0,6', '1,6', '2,5', '4,0', '6,3'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: ['В1Т', 'В2Т'],
        pipePerSection: ['4', '6', '8'],
        passage: ['1', '2', '2а', '4', '4а', '8'],
        ribPipeLength: ['8'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    '2АВЗ-Д': {
        finning: ['9', '20'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['0,6', '1,6', '2,5', '4,0', '6,3'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: ['В1Т', 'В2Т'],
        pipePerSection: ['4', '6'],
        passage: ['1', '2', '2а', '4', '4а', '8'],
        ribPipeLength: ['8'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    'АВМ-Г': {
        finning: ['9', '20'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['0,6', '1,6', '2,5', '4,0', '6,3'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: [],
        pipePerSection: ['4', '6', '8'],
        passage: ['1', '2', '3', '4', '6', '8'],
        ribPipeLength: ['1,5', '3'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    'АВМ-В': {
        finning: ['9', '20'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['0,6', '1,6', '2,5', '4,0', '6,3'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: [],
        pipePerSection: ['4', '6', '8'],
        passage: ['1', '2', '3', '4', '6', '8'],
        ribPipeLength: ['1,5', '3'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
    'АВОГ-1': {
        finning: ['7,8'],
        blinds: ['Ж', 'ПЖ', 'ЭЖ'],
        pressure: ['0,09'],
        matExec: ['Б1', 'Б2', 'Б2.1', 'Б3', 'Б3.1', 'Б4', 'Б4.1', 'Б5', 'Б5.1'],
        fan: ['В3Т'],
        pipePerSection: ['8'],
        passage: ['1'],
        ribPipeLength: ['6'],
        climate: ['УХЛ1', 'У1', 'С'],
    },
};

export const FIELDSET_CONFIG = [
    { groupName: 'type', label: 'Модификация аппарата:', options: typeOptions },
    { groupName: 'finning', label: 'Коэффициент оребрения:', options: finningOptions },
    { groupName: 'blinds', label: 'Жалюзи с приводом:', options: blindsOptions },
    { groupName: 'pressure', label: 'Условное давление, МПа (кгс/см²):', options: pressureOptions },
    { groupName: 'matExec', label: 'Материальное исполнение секций:', options: matExecOptions, helpImageSrc: `${import.meta.env.BASE_URL}images/материальное-исполнение-секций.webp` },
    { groupName: 'fan', label: 'Тип привода вентилятора:', options: fanOptions, helpImageSrc: `${import.meta.env.BASE_URL}images/тип-привода-вентилятора.webp` },
    { groupName: 'pipePerSection', label: 'Число рядов труб в секции:', options: pipePerSectionOptions },
    { groupName: 'passage', label: 'Число ходов по трубному пространству:', options: passageOptions },
    { groupName: 'ribPipeLength', label: 'Длина оребрённых труб в секции:', options: ribPipeLengthOptions },
    { groupName: 'climate', label: 'Климатическое исполнение:', options: climateOptions, helpImageSrc: `${import.meta.env.BASE_URL}images/климатическое-исполнение.webp` },
];

export const initialGroupsState = {
    type: { selectedValue: null, customText: '' },
    finning: { selectedValue: null, customText: '' },
    blinds: { selectedValue: null, customText: '' },
    pressure: { selectedValue: null, customText: '' },
    matExec: { selectedValue: null, customText: '' },
    fan: { selectedValue: null, customText: '' },
    pipePerSection: { selectedValue: null, customText: '' },
    passage: { selectedValue: null, customText: '' },
    ribPipeLength: { selectedValue: null, customText: '' },
    climate: { selectedValue: null, customText: '' },
};